const cities = [
  { cityId: '101', cityName: '阿山', prefix: 'A', isPopular: true },
  { cityId: '102', cityName: '安康', prefix: 'A' },
  { cityId: '103', cityName: '安平', prefix: 'A' },
  { cityId: '104', cityName: '安阳', prefix: 'A' },
  { cityId: '105', cityName: '鞍山', prefix: 'A' },
  { cityId: '106', cityName: '安定', prefix: 'A' },
  { cityId: '107', cityName: '艾河', prefix: 'A' },
  { cityId: '108', cityName: '阿金', prefix: 'A' },
  { cityId: '109', cityName: '阿木', prefix: 'A' },
  { cityId: '110', cityName: '安图', prefix: 'A' },
  { cityId: '111', cityName: '北京', prefix: 'B', isPopular: true },
  { cityId: '112', cityName: '白河', prefix: 'B' },
  { cityId: '113', cityName: '本溪', prefix: 'B' },
  { cityId: '114', cityName: '保定', prefix: 'B' },
  { cityId: '121', cityName: '重庆', prefix: 'C', isPopular: true },
  { cityId: '122', cityName: '长春', prefix: 'C' },
  { cityId: '123', cityName: '成都', prefix: 'C' },
  { cityId: '124', cityName: '长沙', prefix: 'C' },
  { cityId: '131', cityName: '大成', prefix: 'D', isPopular: true },
  { cityId: '132', cityName: '丹东', prefix: 'D' },
  { cityId: '133', cityName: '大理', prefix: 'D' },
  { cityId: '134', cityName: '大连', prefix: 'D' },
  { cityId: '141', cityName: '鄂州', prefix: 'E', isPopular: true },
  { cityId: '142', cityName: '二营', prefix: 'E' },
  { cityId: '143', cityName: '峨眉', prefix: 'E' },
  { cityId: '144', cityName: '二龙', prefix: 'E' },
  { cityId: '151', cityName: '阜阳', prefix: 'F', isPopular: true },
  { cityId: '152', cityName: '丰城', prefix: 'F' },
  { cityId: '153', cityName: '凤城', prefix: 'F' },
  { cityId: '154', cityName: '奉城', prefix: 'F' },
  { cityId: '161', cityName: '广州', prefix: 'G', isPopular: true },
  { cityId: '162', cityName: '古城', prefix: 'G' },
  { cityId: '163', cityName: '高平', prefix: 'G' },
  { cityId: '164', cityName: '古田', prefix: 'G' },
  { cityId: '171', cityName: '合肥', prefix: 'H', isPopular: true },
  { cityId: '172', cityName: '淮安', prefix: 'H' },
  { cityId: '173', cityName: '淮北', prefix: 'H' },
  { cityId: '174', cityName: '邯郸', prefix: 'H' },
  { cityId: '191', cityName: '济南', prefix: 'J', isPopular: true },
  { cityId: '192', cityName: '吉安', prefix: 'J' },
  { cityId: '193', cityName: '晋城', prefix: 'J' },
  { cityId: '194', cityName: '靖江', prefix: 'J' },
  { cityId: '201', cityName: '昆山', prefix: 'K', isPopular: true },
  { cityId: '202', cityName: '喀什', prefix: 'K' },
  { cityId: '203', cityName: '开封', prefix: 'K' },
  { cityId: '204', cityName: '柯城', prefix: 'K' },
  { cityId: '211', cityName: '兰州', prefix: 'L', isPopular: true },
  { cityId: '212', cityName: '刘安', prefix: 'L' },
  { cityId: '213', cityName: '陆川', prefix: 'L' },
  { cityId: '214', cityName: '丽江', prefix: 'L' },
  { cityId: '221', cityName: '漠河', prefix: 'M', isPopular: true },
  { cityId: '222', cityName: '绵阳', prefix: 'M' },
  { cityId: '223', cityName: '梅州', prefix: 'M' },
  { cityId: '224', cityName: '麦田', prefix: 'M' },
  { cityId: '231', cityName: '南京', prefix: 'N', isPopular: true },
  { cityId: '232', cityName: '南昌', prefix: 'N' },
  { cityId: '233', cityName: '南充', prefix: 'N' },
  { cityId: '234', cityName: '宁波', prefix: 'N' },
  { cityId: '251', cityName: '平安', prefix: 'P', isPopular: true },
  { cityId: '252', cityName: '平方', prefix: 'P' },
  { cityId: '253', cityName: '平岗', prefix: 'P' },
  { cityId: '254', cityName: '平果', prefix: 'P' },
  { cityId: '261', cityName: '青岛', prefix: 'Q', isPopular: true },
  { cityId: '262', cityName: '庆安', prefix: 'Q' },
  { cityId: '263', cityName: '泉州', prefix: 'Q' },
  { cityId: '264', cityName: '曲阜', prefix: 'Q' },
  { cityId: '271', cityName: '日照', prefix: 'R', isPopular: true },
  { cityId: '272', cityName: '热水', prefix: 'R' },
  { cityId: '273', cityName: '乳山', prefix: 'R' },
  { cityId: '274', cityName: '如皋', prefix: 'R' },
  { cityId: '281', cityName: '上海', prefix: 'S', isPopular: true },
  { cityId: '282', cityName: '神木', prefix: 'S' },
  { cityId: '283', cityName: '四瓶', prefix: 'S' },
  { cityId: '284', cityName: '商丘', prefix: 'S' },
  { cityId: '291', cityName: '天津', prefix: 'T', isPopular: true },
  { cityId: '292', cityName: '太原', prefix: 'T' },
  { cityId: '293', cityName: '唐山', prefix: 'T' },
  { cityId: '294', cityName: '泰山', prefix: 'T' },
  { cityId: '321', cityName: '武汉', prefix: 'W', isPopular: true },
  { cityId: '322', cityName: '威海', prefix: 'W' },
  { cityId: '323', cityName: '芜湖', prefix: 'W' },
  { cityId: '324', cityName: '渭南', prefix: 'W' },
  { cityId: '331', cityName: '西安', prefix: 'X', isPopular: true },
  { cityId: '332', cityName: '厦门', prefix: 'X' },
  { cityId: '333', cityName: '秀山', prefix: 'X' },
  { cityId: '334', cityName: '徐州', prefix: 'X' },
  { cityId: '341', cityName: '延安', prefix: 'Y', isPopular: true },
  { cityId: '342', cityName: '运城', prefix: 'Y' },
  { cityId: '343', cityName: '盐城', prefix: 'Y' },
  { cityId: '344', cityName: '玉林', prefix: 'Y' },
  { cityId: '351', cityName: '郑州', prefix: 'Z', isPopular: true },
  { cityId: '352', cityName: '珠海', prefix: 'Z' },
  { cityId: '353', cityName: '镇江', prefix: 'Z' },
  { cityId: '354', cityName: '枣庄', prefix: 'Z' },
]

export default cities;